// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrolzzufzmmlsuzldpqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indyb2x6enVmem1tbHN1emxkcHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NTQxMjUsImV4cCI6MjA5MTAzMDEyNX0.ttfxYNAcSRuFD2N81DvENpFnjISr8vbGGhSBhEhQS-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});